# Variables and Data Types

In [1]:
# Variables

X=10 # Here x is a variables it used to store data 
X="Hello" # It's a Dynamic typing 
print(X) # To types of values assained in same variable X 
# It print last stored values in the X variable

Hello

In [2]:
# Data Types

# Numerical Types
# Integer
x = 10  
print(type(x),"x=",x)  # Output: <class 'int'>

# Float
pi = 3.14  
print(type(pi),'pi=',pi)  # Output: <class 'float'>

# Complex number
z = 3 + 4j  
print(type(z),'z=',z)  # Output: <class 'complex'>
print(z.real, z.imag)

#Sequence Typea
# String
name = "Aravind"
print(type(name),'name=',name)  # Output: <class 'str'>

# List (mutable)
fruits = ["apple", "banana", "cherry"] #storing multiple values
fruits.append("mango")  # Adding an item
print('fruites=',fruits)  # Output: ['apple', 'banana', 'cherry', 'mango']

# Tuple (immutable)
coordinates = (10, 20) # fixed data can't be changed
print(type(coordinates),'coordinates=',coordinates)  # Output: <class 'tuple'>

# Range
numbers = range(5)
print(list(numbers),'numbers=',numbers)  # Output: [0, 1, 2, 3, 4]

# Set Types
# Set (unordered, unique values)
unique_numbers = {1, 2, 3, 2} # remove duplicates
print(unique_numbers)  # Output: {1, 2, 3}

# Frozenset (immutable set)
fs = frozenset([1, 2, 3]) # fixed date
print(type(fs),'fs=',fs)  # Output: <class 'frozenset'>

# Mapping Type
# dist
person = {"name": "Aravind", "age": 25} #useful for database-like storage
print(type(person),'person name=',person["name"])  # Output: "Aravind"

# Binary Types
# bytes
b = b'Hello' #used in networking
print(b)  # Output: b'Hello'

# bytearray
ba = bytearray([65, 66, 67])
print(ba)  # Output: bytearray(b'ABC')

# memoryview
mv = memoryview(b'Hello') # used for mv = memoryview(b'Hello')
print(mv[0])  # Output: 72 (ASCII of 'H')

# None Type (Represents missing or undefined values)
result = None #Used where no value is assigned yet
if result is None:
    print("No data available.")  # Output: "No data available."

<class 'int'> x= 10
<class 'float'> pi= 3.14
<class 'complex'> z= (3+4j)
3.0 4.0
<class 'str'> name= Aravind
fruites= ['apple', 'banana', 'cherry', 'mango']
<class 'tuple'> coordinates= (10, 20)
[0, 1, 2, 3, 4] numbers= range(0, 5)
{1, 2, 3}
<class 'frozenset'> fs= frozenset({1, 2, 3})
<class 'dict'> person name= Aravind
b'Hello'
bytearray(b'ABC')
72
No data available.

In [3]:
# Immutable Types (str, tuple, frozenset)
# Immutable data types cannot be changed once defined.

# Strings are immutable
name = "Aravind"
# name[0] = "B"  # This would raise an error

# Tuples are immutable
coordinates = (10, 20)
# coordinates[0] = 5  # This would raise an error

# Frozenset is immutable
fs = frozenset([1, 2, 3])
# fs.add(4)  # This would raise an error

In [4]:
# Mutable Types (list, dict, set, bytearray)
# Mutable data types can be modified after creation.

# Lists are mutable
fruits = ["apple", "banana", "cherry"]
fruits.append("mango")  
print(fruits)  # Output: ['apple', 'banana', 'cherry', 'mango']

# Dictionaries are mutable
person = {"name": "Aravind", "age": 25}
person["age"] = 26  # Modifying the dictionary
print(person)  # Output: {'name': 'Aravind', 'age': 26}

# Sets are mutable
numbers = {1, 2, 3}
numbers.add(4)
print(numbers)  # Output: {1, 2, 3, 4}

# Bytearray is mutable
ba = bytearray([65, 66, 67])
ba[0] = 68
print(ba)  # Output: bytearray(b'DBC')

['apple', 'banana', 'cherry', 'mango']
{'name': 'Aravind', 'age': 26}
{1, 2, 3, 4}
bytearray(b'DBC')

In [5]:
# Conversions Between Types

# Integer to Float
x = 10
y = float(x)  
print(y)  # Output: 10.0

# List to Tuple
my_list = [1, 2, 3]
my_tuple = tuple(my_list)
print(my_tuple)  # Output: (1, 2, 3)

# Dictionary Keys to List
person = {"name": "Aravind", "age": 25}
keys_list = list(person.keys()) # keys to list
values_list = list(set(person.values())) # values to lis
print(keys_list)  # Output: ['name', 'age']
print(values_list) # Output: ['Aravind',25]

10.0
(1, 2, 3)
['name', 'age']
['Aravind', 25]

# Variable Scope and variable Lifetime

##### Variable Scope
1. Local Scope
2. Enclosing Scope
3. Global Scope
4. Built-in Scope

In [6]:
# Local Scope (Variables inside a function)
def local_scope_example():
    x = 5  # Local variable
    print("Inside function:", x)  # Output: Inside function: 5

local_scope_example()
# print(x)  # This would raise an error (x is not accessible outside)

# Enclosing Scope (Variables inside nested functions)
def outer_function():
    y = 10  # Enclosing variable
    
    def inner_function():
        print("Inside inner function:", y)  # Output: Inside inner function: 10
    
    inner_function()
outer_function()

# Global Scope (Variables outside functions)
global_var = "Python"

def global_scope_example():
    print("Inside function:", global_var)

global_scope_example()
print("Outside function:", global_var)  # Output: Outside function: Python

Inside function: 5
Inside inner function: 10
Inside function: Python
Outside function: Python

In [7]:
# Built-in Scope (Predefined variables & functions)

print("Built-in Scope:", abs(-40))  # Output: Built-in Scope: 40
print("ASCII:", ascii("Python™"))   # Output: ASCII: 'Python\u2122'
print("Binary:", bin(5))            # Output: Binary: 0b101
print("Boolean:", bool(0))          # Output: Boolean: False
print("Character:", chr(65))        # Output: Character: A
print("List:", list("hello"))       # Output: List: ['h', 'e', 'l', 'l', 'o']
print("Length:", len([1, 2, 3]))     # Output: Length: 3
print("Maximum:", max([1, 10, 3]))   # Output: Maximum: 10
print("Minimum:", min([1, 10, 3]))   # Output: Minimum: 1
print("Power:", pow(2, 3))          # Output: Power: 8
print("Sorted:", sorted([5, 3, 9]))  # Output: Sorted: [3, 5, 9]
print("Sum:", sum([1, 2, 3]))        # Output: Sum: 6
print("Type:", type(42))            # Output: Type: <class 'int'>
print("Zip:", list(zip([1, 2], ['a', 'b'])))  # Output: Zip: [(1, 'a'), (2, 'b')]

print('\n')
# all()
numbers = [1, 2, 3, 4, 5]  # All are non-zero values
print('non-zero:',all(numbers))  # Output: True

bool_values = [True, True, False]  # One element is False
print('check_false:',all(bool_values))  # Output: False

mixed_list = ['', 'Hello', 'Python']  # Empty string is false
print('Is_empty:',all(mixed_list))  # Output: False

print('\n')
# any()
numbers = [0, 0, 3, 0, 0]  # Only one non-zero value
print('non-zero:',any(numbers))  # Output: True

bool_values = [False, False, False]  # No True values
print('check_false:',any(bool_values))  # Output: False

mixed_list = ['', '', 'Python']  # One non-empty string
print('Is_empty:',any(mixed_list))  # Output: True

print('\n')
#enumerate(iterable)
fruits = ["apple", "banana", "cherry"] # Assigns index to items
print('output:')
for index, fruit in enumerate(fruits):
    print(index, fruit)

print('\n')
# eval(expression) Evaluates a string as Python code
expression = "5 + 10 * 2"
result = eval(expression)  # Evaluates the string as Python expression
print('value:',result)  # Output: 25

print('\n')
# filter(function, iterable) – Filters elements based on a function
numbers = [1, 2, 3, 4, 5, 6, 7, 8]
# Function to check if number is even
def is_even(num):
    return num % 2 == 0

filtered_numbers = list(filter(is_even, numbers))
print('filter:',filtered_numbers)  # Output: [2, 4, 6, 8]

print('\n')
# map()
numbers = [1, 2, 3, 4, 5]

# Using map() to apply the `str` function to each number
string_numbers = list(map(str, numbers))
print('Map_str:',string_numbers)  # Output: ['1', '2', '3', '4', '5']

print('\n')
# range(start, stop, step) – Generates a sequence of numbers
# Generate numbers from 1 to 10 with step 2
numbers = list(range(1, 10, 2))
print('value_range:',numbers)

print('\n')
# round(x, n) – Rounds a number to n decimal places
x = 3.14159

# Round to 2 decimal places
rounded_value = round(x, 2)
print('round_value:',rounded_value)

Built-in Scope: 40
ASCII: 'Python\u2122'
Binary: 0b101
Boolean: False
Character: A
List: ['h', 'e', 'l', 'l', 'o']
Length: 3
Maximum: 10
Minimum: 1
Power: 8
Sorted: [3, 5, 9]
Sum: 6
Type: <class 'int'>
Zip: [(1, 'a'), (2, 'b')]


non-zero: True
check_false: False
Is_empty: False


non-zero: True
check_false: False
Is_empty: True


output:
0 apple
1 banana
2 cherry


value: 25


filter: [2, 4, 6, 8]


Map_str: ['1', '2', '3', '4', '5']


value_range: [1, 3, 5, 7, 9]


round_value: 3.14

### Vaiable Lifetime
variable lifetime refers to how long a variable exists in memory before it is destroyed. It depends on the variable's scope (where it's defined) and when it goes out of use

1. Local Variables (short-lived)
2. Global Variables (long-lived)
3. Enclosing Variables (controlled by outer function)

# Operators
1. Arithmetic operators
2. Comparison operators
4. Logical operators
5. Assignment operators
6. Bitwise operators
7. Identity operators
8. Membership operators

In [8]:
# Arithmetic Operators (Used for mathematical operations)

x = 10
y = 5

print('ADD:',x+y) # Addition +
print('SUB:',x-y) # Subtraction -
print('Mul:',x*y) # Multiplication *
print('Div:',x/y) # Division (returns float) /
print('Mod:',x%y) # Modulus %
print('Power:',x**y) # Expoentiation **
print('Floor:',x//y) # Floor division //

ADD: 15
SUB: 5
Mul: 50
Div: 2.0
Mod: 0
Power: 100000
Floor: 2

In [9]:
# Comparison Operators (Used for logical comparisons)

x = 10 
y = 5

print('Equal:',x==y) # Equal to ==
print('not_equal:',x!=y) # Not equal to !=
print('Greater than:',x>y) # Greater than >
print('Less than:',x<y) # Lessor than <
print('Greater than or equal:',x>=y) # Greater than or equal to >=
print('Less than or equal:',x<=y) # Lesser than or equal to <=

Equal: False
not_equal: True
Greater than: True
Less than: False
Greater than or equal: True
Less than or equal: False

In [10]:
# Logical Operators (Used in Boolean logic)

x = 7

print('AND:',x > 5 and x < 10)  # AND
print('OR:',x > 10 or x < 5)   # OR
print('NOT:',not(x>5))  # NOT

AND: True
OR: False
NOT: False

In [11]:
# Assignment Operators (Used for variable assignment and modification)

x = 5
y = 10

print('y =', y)  # Assign value to variable
x += 5
print('add assign:', x)  # Add and assign +=

x -= 5
print('sub assign:', x)  # sub and assign -=

x *= 5
print('mul assign:', x)  # mul and assign *=

x /= 5
print('div assign:', x)  # div and assign /=

x %= 5
print('mod assign:', x) # mod and assign %=  

x = 5  # Reset x for exponentiation
x **= 5
print('exponentiation assign:', x)  

x = 25  # Reset x for floor division
x //= 5
print('floor assign:', x)

y = 10
add assign: 10
sub assign: 5
mul assign: 25
div assign: 5.0
mod assign: 0.0
exponentiation assign: 3125
floor assign: 5

In [12]:
# Bitwise Operators (Used for binary operations)

x = 5  # Binary: 101
y = 3  # Binary: 011

print('AND:',x & y)  # bitwise AND &
print('OR:',x | y)  # bitwise OR |
print('XOR:',x ^ y)  # bitwise XOR ^
print('NOT',~x)  # bitwise NOT ~
print('LEFT SHIFT:',x << 2)  # bitwise left shift <<
print('RIGHT SHIFT:',x >> 2)  # bitwise right shift >>

AND: 1
OR: 7
XOR: 6
NOT -6
LEFT SHIFT: 20
RIGHT SHIFT: 1

In [13]:
# Identity Operators (Used to compare memory addresses of objects)

a = [1, 2, 3]
b = a  # Assigning the same list reference

print('is:',a is b)  # IS
print('is not:',a is not b)  # NOT IS

is: True
is not: False

In [14]:
# Membership Operators (Used for checking presence in collections)

fruits = ["apple", "banana", "cherry"]

print("banana" in fruits)  # IN
print("grape" not in fruits)  # NOT IN

True
True

#### 1. Write a Python program to check whether a number is even or odd using the modulus (%) operator.

In [15]:
x = int(input('Enter number:'))

if x % 2 == 0:
    print('even')
else:
    print('odd')

Enter number: 6

even

#### 2. Create a program that takes two numbers and swaps their values using arithmetic operators (without using a temporary variable).

In [16]:
x = int(input('Enter number x:'))
y = int(input('Enter number y:'))

x = x + y
y = x-y
x = x - y

print('x:',x)
print('y:',y)

Enter number x: 5
Enter number y: 3

x: 3
y: 5

#### 3. Use bitwise operators to find the result of 5 & 3, 5 | 3, and 5 ^ 3. Explain the output using binary calculations.

In [17]:
x = 5 # 0101
y = 3 # 0011

print(x&y) # output 1 binary value 0001
print(x|y) # output 7 binary value 0111
print(x^y) # output 6 binary value 0110

1
7
6

- 5 = 0101
- 3 = 0011

* & = it like and operator the both binary values 1 value 1 eg., 1*1=1, 0*1= 0, 0*0=0
* | = it like or operator the any one binary value is 1 value 1 eg., 1*1=1, 0*1= 1, 0*0=0
* ^ = it like and operator the both binary values are same value is 0 eg., 1*1=0, 0*1=1, 0*0=0

# Input Handeling

In [18]:
# Method 1
# input()
x = input('Enter value:')
print('x:',x)

# Converting input type
y = int(input('Enter number'))
print('y:',y)

# Multiple input handling -- split()
z = input('Enter value:').split()
print('z:',z)

Enter value: aravind

x: aravind

Enter number 5

y: 5

Enter value: 3 4 5

z: ['3', '4', '5']

In [19]:
# Method 2
# sys.argv[] it working on induduval file and run on commond line

import sys
print("Arguments:", sys.argv) # try to use this method on vs or pycharm and run it in there commond line

Arguments: ['C:\\Users\\aravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel_launcher.py', '-f', 'C:\\Users\\aravi\\AppData\\Roaming\\jupyter\\runtime\\kernel-d4c1eff0-7c2a-4096-ae81-e131db4f3074.json']

# String Handeling

In [20]:
# Creating Strings

text1 = "Hello, Python!"  # Using double quotes
text2 = 'Single quotes work too'
text3 = """Triple quotes allow multiline strings"""

print("\n")
# Accessing Characters in Strings
print("Accessing Characters in Strings")
word = "Python"
print(word[0])  # Output: P
print(word[-1]) # Output: n (Negative indexing)

print("\n")
# Slicing Strings
print("Slicing Strings")
text = "Programming"
print(text[0:7])  # Output: Program
print(text[-4:])  # Output: ming
print(text[::-1]) # Output: gnimmargorP (Reversed)

print("\n")
# String Methods (Common Operations)
print("String Methods (Common Operations)")
sentence = "python is fun"

print(sentence.upper())     # Output: PYTHON IS FUN
print(sentence.lower())     # Output: python is fun
print(sentence.capitalize()) # Output: Python is fun
print(sentence.title())      # Output: Python Is Fun
print(sentence.replace("fun", "awesome"))  # Output: python is awesome
print(sentence.split())  # Output: ['python', 'is', 'fun']

print("\n")
# String Concatenation & Joining
print("String Concatenation & Joining")
# Concatenation using + operator
first = "Hello"
second = "World"
result = first + " " + second  # Output: Hello World
print('concatenate method:',result)

print("\n")
# Joining elements using a separator
words = ["Python", "SQL", "AI"]
joined_text = "-".join(words)  # Output: Python-SQL-AI
print('join method:',joined_text)

print("\n")
# Checking String Properties
print("Checking String Properties")
text = "12345"
print(text.isdigit())  # Output: True
print("hello".isalpha())  # Output: True
print("Python3".isalnum())  # Output: True
print("  space  ".strip())  # Output: space  (Removes leading/trailing spaces)

print("\n")
# Formatting Strings
print("Formatting Strings")
name = "Aravind"
age = 25
# f- string method
print(f"My name is {name} and I am {age} years old.")  
# Output: My name is Aravind and I am 25 years old.

# .formate() method
print("My name is {} and I am {} years old.".format(name, age))  
# Output: My name is Aravind and I am 25 years old.

print("\n")
# Searching in Strings
print("Searching in Strings")
text = "Data Analytics"
print(text.startswith("Data"))  # Output: True
print(text.endswith("Python"))  # Output: False
print(text.find("Ana"))  # Output: 5 (Index where "Ana" starts)

print("\n")
# Escape Characters
print("Escape Characters")
print("Hello\nWorld!")  # \n → Newline  
print("Hello\tWorld!")  # \t → Tab  
print("Python's best feature: \"Simplicity\"")  # Using \" for quotes inside strings

Accessing Characters in Strings
P
n


Slicing Strings
Program
ming
gnimmargorP


String Methods (Common Operations)
PYTHON IS FUN
python is fun
Python is fun
Python Is Fun
python is awesome
['python', 'is', 'fun']


String Concatenation & Joining
concatenate method: Hello World


join method: Python-SQL-AI


Checking String Properties
True
True
True
space


Formatting Strings
My name is Aravind and I am 25 years old.
My name is Aravind and I am 25 years old.


Searching in Strings
True
False
5


Escape Characters
Hello
World!
Hello	World!
Python's best feature: "Simplicity"

#### 1. Write a function that counts how many times each character appears in a given string

In [21]:
text = "Write a function that counts how many times each character appears in a given string"

count_words = len(text.split())
print("count of words in text variable:",count_words)

def repeated_char_count(text):
    char_count = {} #initialize empty dict
    for char in text:
        if char in char_count:
            char_count[char] += 1
        else:
            char_count[char] = 1
    return char_count

print("characted Count:",repeated_char_count(text))

count of words in text variable: 15
characted Count: {'W': 1, 'r': 5, 'i': 6, 't': 8, 'e': 6, ' ': 14, 'a': 9, 'f': 1, 'u': 2, 'n': 7, 'c': 5, 'o': 3, 'h': 4, 's': 4, 'w': 1, 'm': 2, 'y': 1, 'p': 2, 'g': 2, 'v': 1}

#### 2. Check whether two strings are anagrams (contain the same letters in a different order).

In [22]:
# exampe
text1 = 'silent'
text2 = 'listen'
text = sorted(text1)
print(text)

['e', 'i', 'l', 'n', 's', 't']

In [23]:
text1 = 'silent'
text2 = 'listen'

def anagram(text1,text2):
    return sorted(text1) == sorted(text2)

if anagram(text1,text2):
    print("It is anagram")
else:
    print("It is not anagram")

It is anagram

# Condition statement
if,else,elif,nested if

In [24]:
# if statement
print("if statement")

age = 18
if age >= 18:
    print("You are eligible to vote.")

print('\n')
# if-else statement
print('if-else statement')

num = 10
if num % 2 == 0:
    print("Even number")
else:
    print("Odd number")

print('\n')
# if-elif-else statement
print('if-elif-else statement')

marks = 75
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
else:
    print("Grade: C")

print('\n')
# nested if statement
print('nested if statement')

score = 95
if score >= 50:
    if score >= 90:
        print("Excellent performance!")
    else:
        print("Good performance!")
else:
    print("Needs improvement.")

if statement
You are eligible to vote.


if-else statement
Even number


if-elif-else statement
Grade: B


nested if statement
Excellent performance!

#### 1. Develop a program where a user enters a temperature, and if it's above 30°C, print "It's hot!", otherwise print "It's cool!"

In [25]:
temperature = int(input('Enter the temperature in C:'))

if temperature >= 30:
    print("It's hot!")
else:
    print("It's cool!")

Enter the temperature in C: 41

It's hot!

#### 2. Write a program that asks the user for a day of the week and prints:"Weekend" for Saturday and Sunday,"Weekday" for Monday to Friday.

In [26]:
day = input('Enter the day:').lower()
week_days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']

if day in week_days[:5]:
    print("weekday")
elif day in week_days[-2:]:
    print("weekend")
else:
    print("The user value is incorrect")

Enter the day: sunday

weekend

#### 3. Create a Python script that checks if a number is divisible by both 3 and 5:
######      If true, print "Divisible by both 3 and 5."
######      If it's only divisible by 3, print "Divisible by 3."
######      If it's only divisible by 5, print "Divisible by 5."
######      Otherwise, print "Not divisible by 3 or 5."

In [27]:
num = int(input("Enter the number: "))

if num % 3 == 0 or num % 5 == 0:  
    if num % 3 == 0:  
        if num % 5 == 0:  
            print(f"{num} is Divisible by both 3 and 5")
        else:
            print(f"{num} is Divisible by 3")
    elif num % 5 == 0:  
        print(f"{num} is Divisible by 5")
else:
    print(f"{num} is Not divisible by 3 or 5")

Enter the number:  53

53 is Not divisible by 3 or 5

# Loops
for,while,nested, break and continue

In [28]:
# for loop
print('for loop')

fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

# while loop
print('\n')
print('while loop')

count = 1
while count <= 5:
    print(count)
    count += 1

# nested loop same as nedted loop in condition statment
print('\n')
print('nested loop')

for i in range(1, 4):  # Outer loop (rows)
    for j in range(1, 4):  # Inner loop (columns)
        print(f"{i} x {j} = {i * j}")

# break condition in for
print('\n')
print('break condition in for')

fruits = ["apple", "banana", "cherry", "mango"]
for fruit in fruits:
    if fruit == "cherry":
        break
    print(fruit)

# continue codition in for 
print('\n')
print('continue codition in for')

fruits = ["apple", "banana", "cherry", "mango"]
for fruit in fruits:
    if fruit == "banana":
        continue
    print(fruit)

for loop
apple
banana
cherry


while loop
1
2
3
4
5


nested loop
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9


break condition in for
apple
banana


continue codition in for
apple
cherry
mango

#### 1. Write a Python program that prints numbers from 1 to 20, but:
If the number is divisible by 4, print "Divisible by 4" instead of the number.
If the number is divisible by 6, print "Divisible by 6" instead of the number.
If divisible by both, print "Divisible by 4 and 6"

In [29]:
for i in range(1,21):
    if i%4==0 and i%6==0:
        print(f"{i} Divisible by 4 and 6")
    elif i%4==0:
        print(f"{i} Divisible by 4")
    elif i%6==0:
        print(f"{i} Divisible by 6")
    else:
        print(i)

1
2
3
4 Divisible by 4
5
6 Divisible by 6
7
8 Divisible by 4
9
10
11
12 Divisible by 4 and 6
13
14
15
16 Divisible by 4
17
18 Divisible by 6
19
20 Divisible by 4

#### 2. Write a program that takes a list of numbers and:
######     Uses a for loop to classify each number as even or odd.
######     Stores even numbers in one list and odd numbers in another.
######     Example list: [10, 7, 22, 15, 33, 42]

In [30]:
num = [10, 7, 22, 15, 33, 42]

for i in num:
    if i%2==0:
        print (f"{i} is even number")
    else:
        print (f"{i} is odd number")

10 is even number
7 is odd number
22 is even number
15 is odd number
33 is odd number
42 is even number

#### 3. Write a Python script that prints the following pattern using nested loops:
###### *
###### **
###### ***
###### ****
###### *****

In [31]:
for i in range(1,6): # Outer loop for rows 
    for j in range(i): # Inner loop for stars
        print('*',end='') # Prints stars
    print() # Moves to the next line

*
**
***
****
*****

In [32]:
rows = 5  # Number of rows in the pyramid

for i in range(1, rows + 1):  # Outer loop for rows
    for j in range(rows - i):  # Inner loop for spaces before stars
        print(" ", end="")  # Prints leading spaces
    for k in range(2 * i - 1):  # Inner loop for stars
        print("*", end="")  # Prints stars
    print()  # Moves to the next line

    *
   ***
  *****
 *******
*********

#### 4. write a code for adding production in cart with while loop

In [36]:
items = []

while True:
    item = input("Add item {if you finish add item to cart type 'done'}: ")
    if item.lower()== 'done':
        break
    items.append(item)
print("shoping finished")

Add item {if you finish add item to cart type 'done'}:  saop
Add item {if you finish add item to cart type 'done'}:  milk
Add item {if you finish add item to cart type 'done'}:  done

shoping finished

# Functions

In [ ]:
# Defining a Function
print('Defining a Function')

def greet():
    print("Hello, welcome to Python!")
greet()  # Calling the function


# Function with Parameters
print('\nFunction with Parameters')

def greet_user(name):
    print(f"Hello, {name}!")
greet_user("Aravind")  # Calling the function with an argument


# Function with Return Value
print('\nFunction with Return Value')

def add_numbers(a, b):
    return a + b  # Returns the sum of a and b  
result = add_numbers(5, 10)  # Calling the function and storing the result
print(f"Sum: {result}")  


# Function with Default Parameters
print('\nFunction with Default Parameters')   

def greet(name="Guest"):
    print(f"Hello, {name}!")  # Default name is "Guest"
greet()  # Calls with default parameter


# Lambda (Anonymous) Functions
print('/nLambda (Anonymous) Functions')

square = lambda x: x * x  # Lambda function to square a number
print(f"Square of 5: {square(5)}") 

#Function with Multiple Returns
print('/nFunction with Multiple Returns')
def get_values(a,b):
    return a+b, a-b, a*b, a/b  # Returns multiple values as a tuple
result = get_values(10, 5)  # Calling the function
print(f"Sum: {result[0]}, Difference: {result[1]}, Product: {result[2]}, Quotient: {result[3]}")

# Function with Variable Arguments (*args and **kwargs)
print('\nFunction with Variable Arguments (*args and **kwargs)')
def greet(*args, **kwargs):
    for name in args:
        print(f"Hello, {name}!")
    for key, value in kwargs.items():
        print(f"{key}: {value}")
greet("Alice", "Bob", age=25, city="New York")  # Passing variable arguments


# Recursive Function
print('\nRecursive Function')
def factorial(n):
    if n == 0 or n == 1:
        return 1  # Base case
    else:
        return n * factorial(n - 1)  # Recursive call
result = factorial(5)  # Calling the recursive function
print(f"Factorial of 5: {result}")

Defining a Function
Hello, welcome to Python!


Function with Parameters
Hello, Aravind!


Function with Return Value
Sum: 15


Function with Default Parameters
Hello, Guest!


Lambda (Anonymous) Functions
Square of 5: 25


Function with Multiple Returns
Sum: 15, Difference: 5, Product: 50, Quotient: 2.0


Function with Variable Arguments (*args and **kwargs)
Hello, Alice!
Hello, Bob!
age: 25
city: New York


Recursive Function
Factorial of 5: 120

I tested some def funtion with a simple example. 
I used def_function_call.py that contain the def function and test.py as the test file.
It seems the function contain file is called by anytime we want that function at anywhere.

# High Order Function (HOF)

In [35]:
# High Order Functions
def square(x):
    return x * x
def cube(x):
    return x * x * x
def apply_function(func, value):
    return func(value)

# Using the high order function
print("Square of 5:", apply_function(square, 5))  # Output: Square

print('\n')
# Using another high order function
def email_validator(domain):
    def is_valid_email(name):
        return f"{name}@{domain}"  # Returns a formatted email address
    return is_valid_email

# Using the high order function
gmail = email_validator("gmail.com")
yahoo = email_validator("yahoo.com")
print("Gmail:", gmail("aravind"))

Square of 5: 25


Gmail: aravind@gmail.com

# Lambda function 
map, filter,reduce or sorted

In [ ]:
# lambda function
square = lambda x: x * x
print(square(5))  # Output: 25

# Lambda with Multiple Arguments
print('\nLambda with Multiple Arguments:')
add = lambda a, b: a + b
print(add(3, 7))  

# Lambda with Conditional Expression
print('\nLambda with Conditional Expression:')
max_value = lambda a, b: a if a > b else b
print(max_value(10, 20))  

# Lambda with map()
print('\nLambda with map():')
numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(lambda x: x * x, numbers))  # Squaring each number
print(squared_numbers)  

# Lambda with filter()
print('\nLambda with filter():')
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))  # Filtering even numbers
print(even_numbers)  

# Lambda with reduce()
print('\nLambda with reduce():')
from functools import reduce
product = reduce(lambda x, y: x * y, numbers)  # Calculating product of all numbers
print(product)  

# Lambda with sorted()
print('\nLambda with sorted():')
numbers = [5, 2, 8, 1, 9]
sorted_numbers = sorted(numbers, key=lambda x: x)  # Sorting numbers
print(sorted_numbers)

25

Lambda with Multiple Arguments:
10

Lambda with Conditional Expression:
20

Lambda with map():
[1, 4, 9, 16, 25]

Lambda with filter():
[2, 4]

Lambda with reduce():
120

Lambda with sorted():
[1, 2, 5, 8, 9]

### closure, partial, Function composition, Callback function, Recursive function, Generator & yield

In [1]:
# closure function
print('Closure Function:')
def outer_function(x):
    def inner_function(y):
        return x + y  # Inner function uses outer function's variable
    return inner_function
closure = outer_function(10)  # Creating a closure with x=10
print(closure(5))  

# Partial Function
print('\nPartial Function:')
from functools import partial
def greet(name, age):
    return f"Hello, {name}! You are {age} years old."
partial_greet = partial(greet, age=30)  # Fixing age to 30
print(partial_greet("Aravind"))  

# Function Annotations
print('\nFunction Annotations:')
def greet(name: str, age: int):
    return f"Hello, {name}! You are {age} years old."
print(greet("Aravind", 25))  # Calling the function with annotations

# Function Composition
print('\nFunction Composition:')
def add(x):
    return x + 2
def multiply(x):
    return x * 3
def compose_functions(f, g):
    def composed_function(x):
        return f(g(x))
    return composed_function
composed = compose_functions(add, multiply)  # Composing add and multiply functions
print(composed(5))  # Calling the composed function with 5

# Callback Functions
print('\nCallback Functions:')
def greet(name):
    return f"Hello, {name}!"
def process_data(data, callback):
    return callback(data)
result = process_data("Aravind", greet)  # Passing greet as a callback function
print(result) 

# Recursion function
print('\nRecursion Function:')
def factorial(n):
    if n == 0:  # Base case
        return 1
    else:
        return n * factorial(n - 1)
result = factorial(5)  # Calling the recursive function
print(f"Factorial of 5: {result}") 

# Generator & Yield function
print('\nGenerator & Yield Function:')
def infinite():
    n = 0
    while True:
        yield n  # Yielding the next value in the sequence
        n += 1
gen = infinite()  # Creating a generator object
print(next(gen))

Closure Function:
15

Partial Function:
Hello, Aravind! You are 30 years old.

Function Annotations:
Hello, Aravind! You are 25 years old.

Function Composition:
17

Callback Functions:
Hello, Aravind!

Recursion Function:
Factorial of 5: 120

Generator & Yield Function:
0

# Classes & Objects
1. Constructor, Instance Variables
2. Inheritance - Single Inheritance, Multiple Inheritance, Multilevel Inheritance, Hierarchical Inheritance, Hybrid
3. Abstraction
4. Polymorphism
5. Encapsulation
6. Access Specifiers

In [31]:
# Constructors 
print('Constructors:')
class parent:
    def __init__(self,name): # Constructor method
        self.name = name # Initial Instance Variables
    def dad(self):
        print(f"I am father from {self.name}")
    def mom(self):
        print(f"I am mother from {self.name}")
p= parent('parent class') # Creating an instance of parent class
print(p.name)  # Accessing the name attribute
p.dad()  # Calling method from parent class
p.mom()  # Calling method from parent class

# Destructors
print('\n')
'''
A destructor is used to perform cleanup operations like:

Closing files
Releasing network or database connections
Freeing up memory or other resources
'''

print('Destructors:')
class FileHandler:
    def __init__(self, filename):
        self.file = open(filename, 'w')
        print("File opened.")

    def write_data(self, data):
        self.file.write(data)

    def __del__(self):
        self.file.close()
        print("File closed.")

handler = FileHandler("sample.txt")
handler.write_data("Hello, Aravind!")

Constructors:
parent class
I am father from parent class
I am mother from parent class


Destructors:
File opened.
File closed.

In [21]:
# Inheritance 

# Single Inheritance
print("single Inheritance:")

class family:  # Parent class
    def car(self):
        print("family car is ford mustang")
class parent(family):  # Child class inheriting from family
    def son(self):
        print("family car is now your's")
p = parent()
p.car()  # Calling method from parent class
p.son()  # Calling method from child class

# Multiple Inheritance
print('\n')
print("Multiple Inheritance:")

class family:  # Parent class
    def car(self):
        print("family car is ford mustang")
    def bike(self):
        print("family bike is honda")
class parent(family):  # Child class inheriting from family
    def father(self):
        print("family car is for sales")
class childern(parent):  # Another child class inheriting from parent
    def son(self):
        print("family bike is now your's")

p = childern()
p.car()  # Calling method from parent class 
p.bike()  # Calling method from parent class
p.father()  # Calling method from parent class
p.son()  # Calling method from child class

# Hierarchical Inheritance
print('\n')
print("Hierarchical Inheritance:")

class animal:  # Parent class
    def sound(self):
        print("Animal makes sound")
class dog(animal):  # Child class inheriting from animal
    def bark(self):
        print("Dog barks")
class cat(animal):  # Another child class inheriting from animal
    def meow(self):
        print("Cat meows")
d = dog()
d.sound()  # Calling method from parent class
d.bark()  # Calling method from child class
print('\n')
c = cat()
c.sound()  # Calling method from parent class
c.meow()  # Calling method from child class

# Multiple Inheritance
print('\n')
print("Multiple Inheritance:")

class vehicle:  # Parent class
    def start(self):
        print("Vehicle started")
class two_wheeler():  # Child class inheriting from vehicle
    def ride(self):
        print("Riding two-wheeler")
class four_wheeler():  # Another child class inheriting from vehicle
    def drive(self):
        print("Driving four-wheeler")
class bike(two_wheeler, vehicle):  # Multiple inheritance
    def bike_ride(self):
        print("Riding bike")
class car(four_wheeler, vehicle):  # Multiple inheritance
    def car_drive(self):
        print("Driving car")    

b = bike()
b.start()  # Calling method from parent class
b.ride()  # Calling method from child class
b.bike_ride()  # Calling method from child class

print('\n')
c = car()
c.start()  # Calling method from parent class
c.drive()  # Calling method from child class
c.car_drive()  # Calling method from child class

# Hybrid Inheritance
print('\n')
print("Hybrid Inheritance:")

class animal:  # Parent class
    def sound(self):    
        print("Animal makes sound")
class dog(animal):  # Child class inheriting from animal
    def bark(self):
        print("Dog barks")
class cat(animal):  # Another child class inheriting from animal
    def meow(self):
        print("Cat meows")
class pet(dog, cat):  # Hybrid inheritance
    def pet_sound(self):
        print("Pet makes sound")
p = pet()
p.sound()  # Calling method from parent class
p.bark()  # Calling method from child class
p.meow()  # Calling method from another child class

single Inheritance:
family car is ford mustang
family car is now your's


Multiple Inheritance:
family car is ford mustang
family bike is honda
family car is for sales
family bike is now your's


Hierarchical Inheritance:
Animal makes sound
Dog barks


Animal makes sound
Cat meows


Multiple Inheritance:
Vehicle started
Riding two-wheeler
Riding bike


Vehicle started
Driving four-wheeler
Driving car


Hybrid Inheritance:
Animal makes sound
Dog barks
Cat meows

In [25]:
# Abstruction 
''' 
if we don't call the abstract method in child class it will raise an error
so we need to call the abstract method in child class 
without the abstract method it will not raise an error but it will not work as expected

check it out give the comment line on one of the abstractmethod it causes an error 
'''

from abc import ABC, abstractmethod # Importing ABC and abstractmethod from abc module

class webapp(ABC):  # Abstract base class
    @abstractmethod
    def login(self):
        pass  # Abstract method with no implementation

    @abstractmethod
    def logout(self):
        pass  # Abstract

    def checkout(self):
        print("Checkout process")  # Concrete method with implementation

class website1(webapp):  # Inheriting from abstract base class
    def login(self):
        print("Login to website1")  # Implementing abstract method

    def logout(self):
        print("Logout from website1")  # Implementing abstract method

class website2(webapp):  # Inheriting from abstract base class
    def login(self):    
        print("Login to website2")  # Implementing abstract method  

    def logout(self):
        print("Logout from website2")  # Implementing abstract method

wa = website1()  # Creating an instance of website1
wa.login()  # Calling login method
wa.logout()  # Calling logout method

wb = website2()  # Creating an instance of website2
wb.login()  # Calling login method
wb.logout()  # Calling logout method

Login to website1
Logout from website1
Login to website2
Logout from website2

In [33]:
# Polymorphism
# Dynamic typeing polymorphism allows methods to be overridden in child classes
print('\nDynamic Typing Polymorphism:')
class Bird:
    def fly(self):
        print("Bird is flying.")

class Plane:
    def fly(self):
        print("Plane is flying.")

def start_flight(thing):
    thing.fly()

start_flight(Bird())   # Bird is flying
start_flight(Plane())  # Plane is flying

# Function Overriding
print('\nFunction Overriding:')

class Shape:
    def area(self):
        pass

class Circle(Shape):
    def area(self):
        return 3.14 * 5 * 5  # Area of a circle with radius 5

class Rectangle(Shape):
    def area(self):
        return 10 * 4  # Area of a rectangle

shapes = [Circle(), Rectangle()]

for shape in shapes:
    print(shape.area())

Dynamic Typing Polymorphism:
Bird is flying.
Plane is flying.

Function Overriding:
78.5
40

In [46]:
# Access Modifiers or access specifiers
print('Access Modifiers:')
print('\nPublic: Accessible from anywhere')
class PublicClass:
    def __init__(self, name="Public Class"):
        self.name = name
    def public_method(self):
        print(f"This method is {self.name}.")
pulic= PublicClass()
pulic.public_method()  # Accessible from anywhere

# Protected: Accessible within the class and its subclasses
print('\nProtected: Accessible within the class and its subclasses')
class ProtectedClass:
    def __init__(self, name="Protected Class"):
        self._name = name  # Protected attribute
    def protected_method(self):
        print(f"This method is {self._name}.")
class SubProtectedClass(ProtectedClass):
    def sub_protected_method(self):
        print(f"Sub class method is {self._name}.")
protected = SubProtectedClass()
protected.protected_method()  # Accessible within the subclass
protected.sub_protected_method()  # Accessible within the subclass

# Private: Accessible only within the class
print('\nPrivate: Accessible only within the class')
class PrivateClass:
    def __init__(self, name="Private Class"):
        self.__name = name  # Private attribute
    def __private_method(self):
        print(f"This method is {self.__name}.")
    def access_private_method(self):
        self.__private_method()  # Accessing private method within the class
class PublicPrivateClass(PrivateClass):
    def public_method(self):
        print("Accessing private method from public method:")
        self.access_private_method()  # Accessing private method through a public method
private = PrivateClass()
private.access_private_method()  # Accessing private method through a public method
public_private = PublicPrivateClass()
public_private.public_method()  # Accessing private method through a public method

Access Modifiers:

Public: Accessible from anywhere
This method is Public Class.

Protected: Accessible within the class and its subclasses
This method is Protected Class.
Sub class method is Protected Class.

Private: Accessible only within the class
This method is Private Class.
Accessing private method from public method:
This method is Private Class.

#### example of access specifier Student Record System that uses all three access specifiers — public, protected, and private — to manage information securely and clearly.

In [52]:
# The code has written outter file and it called in this file
# Classes and Object Calling from classes_object_calling.py file 
# Importing the Student class from classes_object_calling module

from classes_object_calling import Student  # Importing the Student class from class&object_calling module

s1 = Student("Aravind", 101, "A+", "secure@123")

# Public access
s1.display_public_info()

# Protected access (allowed, but by convention should be used carefully)
s1.display_protected_info()

# Proper way to access private info
s1.access_private_info()

Name: Aravind, Roll No: 101
Grade (protected): A+
Accessing private info safely:
[Private] Password: secure@123

In [ ]:
'''Encapsulation it is a concept of wrapping data and methods into a single unit (class) 
to restrict direct access to some of the object's components. It helps in data hiding and abstraction, 
ensuring that the internal representation of an object is hidden from the outside.'''
print('Encapsulation:')

class bank:
    def __init__(self, account_number, balance):
        self.__account_number = account_number  # Private attribute
        self.__balance = balance  # Private attribute

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"\nDeposited: {amount} \nNew Balance: {self.__balance}")
        else:
            print("Invalid deposit amount.")

    def withdraw(self, amount):
        if 0 < amount <= self.__balance:
            self.__balance -= amount
            print(f"\nWithdrawn: {amount}. \nNew Balance: {self.__balance}")
        else:
            print("Invalid withdrawal amount or insufficient funds.")

    def get_balance(self):
        return self.__balance  # Accessing private attribute through a public method

bank_account = bank("123456789", 1000)
bank_account.deposit(500)  # Depositing money
print(f"Current Balance: {bank_account.get_balance()}")  # Getting current balance

bank_account.withdraw(200)  # Withdrawing money
print(f"Current Balance: {bank_account.get_balance()}")  # Getting current balance

Encapsulation:

Deposited: 500
New Balance: 1500
Current Balance: 1500

Withdrawn: 200.
New Balance: 1300
Current Balance: 1300

### Instance,class,static methods

In [13]:
# Instance,class,static methods

class MathOperations:
    def __init__(self):
        self.a = 4
        self.b = 5

    @staticmethod
    def add(a, b):
        return a + b

    @classmethod
    def multiply(cls):
        # For demonstration, use default values or create an instance
        instance = cls()
        return instance.a * instance.b

    def instance_method(self):
        return self.a - self.b

math_ops = MathOperations()
print("Static Method (Add):", MathOperations.add(4, 5))  
print("Class Method (Multiply):", MathOperations.multiply())  
print("Instance Method (Subtract):", math_ops.instance_method())

Static Method (Add): 9
Class Method (Multiply): 20
Instance Method (Subtract): -1

# File Handling
1. CSV
2. JSON
3. XML

In [17]:
file= open('sample.txt', 'w') 
file.write("Hello, Aravind!") 
file.close()

In [15]:
# Create or overwrite a file
with open("example.txt", "w") as file:
    file.write("Hello, Aravind!\n")
    file.write("Welcome to file handling in Python.")

# Read the file
with open("example.txt", "r") as file:
    content = file.read()
    print("File Content:")
    print(content)

# Append to the file
with open("example.txt", "a") as file:  
    file.write("\nThis is an appended line.")

# Read line by line
with open("example.txt", "r") as file:
    for line in file:
        print(line.strip())

File Content:
Hello, Aravind!
Welcome to file handling in Python.
Hello, Aravind!
Welcome to file handling in Python.
This is an appended line.

In [16]:
# Delete the file
import os
if os.path.exists("example.txt"):
    os.remove("example.txt")
    print("File deleted successfully.")
else:
    print("File does not exist.")

File deleted successfully.

In [20]:
# CSV File Handling
import csv
# Writing to a CSV file
with open("data.csv", "w", newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["Name", "Age", "City"])
    writer.writerow(["Aravind", 25, "New York"])
    writer.writerow(["Alice", 30, "Los Angeles"])

In [ ]:
# another way to write,read csv file usin pandas
import pandas as pd
df = pd.read_csv("data.csv")
df

      Name  Age         City
0  Aravind   25     New York
1    Alice   30  Los Angeles

In [22]:
# json File Handling
import json

data = {"name": "Aravind", "age": 21, "skills": ["Python", "SQL"]}

with open("data.json", "w") as file:
    json.dump(data, file, indent=4)

In [23]:
# another way to read json file using pandas
df = pd.read_json("data.json")
df

      name  age  skills
0  Aravind   21  Python
1  Aravind   21     SQL

In [28]:
# xml File Handling
from openpyxl import load_workbook
from openpyxl import Workbook

wb = Workbook()
sheet = wb.active
sheet["A1"] = "Name"
sheet["B1"] = "Grade"
sheet.append(["Aravind", "A"])
sheet.append(["Divya", "B"])
wb.save("student.xlsx")

wb = load_workbook("student.xlsx")
sheet = wb.active
print(sheet["A1"].value)  # Output: Name

Name

In [31]:
# another way to read xml file using pandas
df = pd.read_excel("student.xlsx")
df

      Name Grade
0  Aravind     A
1    Divya     B

# Exception Handling

In [32]:
# Exception Handling
try:
    num = int(input("Enter a number: "))
    result = 100 / num
    print(f"Result: {result}")
except ValueError:
    print("Invalid input! Please enter a valid number.")
except ZeroDivisionError:
    print("Division by zero is not allowed!")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
# Finally block
finally:
    print("Execution completed.")

Division by zero is not allowed!
Execution completed.

# DB Connectivity to mysql

In [1]:
import pymysql

try:
    conn = pymysql.connect(
        host="localhost",
        user="root",
        password="@Aravind2004",  # Use the actual password string here, not URL encoded
        database="learn_sql",
    )
    print("Connected!")
except pymysql.MySQLError as e:
    print(f"Connection failed: {e}")
    conn = None

if conn:
    cursor = conn.cursor()

    # Drop table if exists to avoid schema mismatch
    cursor.execute("DROP TABLE IF EXISTS students_new")
    # Create table
    cursor.execute("""
    CREATE TABLE students_new (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100),
        grade VARCHAR(10)
    )
    """)

    # Insert data
    cursor.execute("INSERT INTO students_new (name, grade) VALUES (%s, %s)", ("Aravind", "A"))
    conn.commit()

    # Read data
    cursor.execute("SELECT * FROM students_new")
    for row in cursor.fetchall():
        print(row)

    cursor.close()
    conn.close()

Connected!
(1, 'Aravind', 'A')

# pytest

* It is the testing framework of python . It is used to write test cases for the code. It is very powerful and flexible.
* It runs under the cdl or terminal - python -m pytest (filename)